#version : '3.9'

services:
  # nginx:
  #   build: ./microservices/nginx/
  #   ports:
  #     - "8080:80"
  #   env_file: .env
  #   networks:
  #     - default
  
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    networks:
      - default

  trannscendence:
    build: ./microservices/transcendence/
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - default
    depends_on:
      - db
    volumes:
      - ./microservices/transcendence:/app

volumes:
  postgres_db:
  
networks:
  default:
