events{}

http{
	#upstream django{
	#	server django_servername:port;
	#}
	server{
		listen 80;
		listen [::]:80;
		server_name default_server;
		#location / {
		#	proxy_pass http://django_servername;
		#}
	}
}
