# Generated by Django 4.2.3 on 2024-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='https://profile.intra.42.fr/images/default.png', max_length=200, null=True),
        ),
    ]
